# Generated by Django 5.0.3 on 2024-04-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_barbershop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='user',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='user_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
