# Generated by Django 5.0.3 on 2024-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_styleofcut_name_alter_styleofcut_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleofcut',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='styleofcut',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
