# Generated by Django 5.0.3 on 2024-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
    ]
