# Generated by Django 5.0.3 on 2024-04-07 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_barbershop_in_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Service rating from 1 (Poor) to 5 (Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rating_comment',
            field=models.TextField(blank=True, help_text='Comments on the service', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_rated',
            field=models.BooleanField(default=False, help_text='Indicates if the service has been rated'),
        ),
    ]
