# Generated by Django 5.0.3 on 2024-04-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_device_token_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='user',
        ),
        migrations.AddField(
            model_name='barber',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='api.barbershop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barber',
            name='name',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barber',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
