# Generated by Django 5.0.3 on 2024-04-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_barber_user_barber_address_barber_barbershop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.barber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='style_of_cut',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
