# Generated by Django 5.0.3 on 2024-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barbershop_images'),
        ),
    ]
