# Generated by Django 5.0.3 on 2024-04-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_barber_barbershop_styleofcut_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='barber',
        ),
    ]
