# Generated by Django 5.0.3 on 2024-04-07 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_rating_appointment_rating_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
